-- Run this script in your Supabase SQL Editor

-- 1. Create the reviews table
create table public.reviews (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  position text not null,  -- This maps to 'role' in your form
  company text not null,
  review text not null,
  rating integer default 5,
  avatar text,
  is_approved boolean default false
);

-- 2. Enable Row Level Security (RLS)
alter table public.reviews enable row level security;

-- 3. Create Policy: Allow anyone to insert (submit) a review
create policy "Allow public submissions"
on public.reviews
for insert
to public
with check (true);

-- 4. Create Policy: Allow anyone to read APPROVED reviews only
create policy "Allow public read of approved reviews"
on public.reviews
for select
to public
using (is_approved = true);

-- 5. (Optional) Grant access to anon role if not automatically done
grant select, insert on table public.reviews to anon;
